### ISSUE TITLE
bug: regression on nuxt@3.13.2 breaking the entire module

### ISSUE THREAD

**Issue by tobychidi** [nuxt-modules/leaflet#80] opened 2024-09-16 08:27 UTC
The requested module '/_nuxt/@fs/C:/Users/tobychidi/Documents/GitHub/kaycee/Rotabliss/node_modules/.pnpm/@vue-leaflet+vue-leaflet@0.10.1_@types+leaflet@1.9.12_leaflet@1.9.4_typescript@5.6.2/node_modules/@vue-leaflet/vue-leaflet/dist/vue-leaflet.cjs.js?v=6cbe18fd' does not provide an export named 'LTileLayer'

![image](https://github.com/user-attachments/assets/0f84c8c4-d6c1-4fcf-b074-b1e00df5a8ad)

**Comment by Gugustinette** [comment] 2024-09-16 12:07
Ooh that's weird, can you provide a reproduction ?

**Comment by urbgimtam** [comment] 2024-09-16 13:24
Suffering the same after updating to nuxt@3.13.2.

[Reproduction](https://stackblitz.com/edit/nuxt-starter-riv7th?file=app.vue)

**Comment by urbgimtam** [comment] 2024-09-16 13:35
Forcing nuxt@3.13.1 does not trigger error. Only 3.13.2

**Comment by cesxhin** [comment] 2024-09-16 14:01
same problem, after updating to nuxt@3.13.2

**Comment by Gugustinette** [comment] 2024-09-17 12:37
After further investigations, I think this is more or less due to [this fix](https://github.com/nuxt/nuxt/pull/28843) from [nuxt@3.13.2](https://github.com/nuxt/nuxt/releases/tag/v3.13.2).

But I'm really not sure what should be changed on the module side, this is how components from [vue-leaflet](https://github.com/vue-leaflet/vue-leaflet) are imported :
```typescript
for (const component of components) {
  addComponent({
    name: component,
    export: component,
    filePath: '@vue-leaflet/vue-leaflet',
    chunkName: `nuxt-leaflet/${component}`,
    mode: 'all',
  })
}
```

@danielroe any suggestion on this ?

You can develop on the module playground directly here : https://stackblitz.com/~/github.com/nuxt-modules/leaflet and try to navigate to `/map/map` path, which displays the following error :
![Capture d’écran 2024-09-17 à 14 36 20](https://github.com/user-attachments/assets/deb401fe-db23-45cb-b9f7-f9feba4c6937)

**Comment by danielroe** [comment] 2024-09-17 13:17
yes, this is a nuxt bug.

**Comment by Gugustinette** [comment] 2024-09-17 15:20
Re-opening until the fix is released, for now stick with [`nuxt@3.13.1`](https://github.com/nuxt/nuxt/releases/tag/v3.13.1)

**Comment by ipanamski** [comment] 2024-09-17 15:27
Is the fix going to be included in the next release or the current one 3.13.2?

**Comment by Gugustinette** [comment] 2024-09-17 15:52
@ipanamski You'll have to wait for a new release, I'll update this issue when it is available 👍

**Comment by urbgimtam** [comment] 2024-09-17 18:08
It may be interesting to remind that it can be mitigated by wrapping `<NuxtErrorBoundary>` around your component which holds `<LMap>`, and even pass alternative content with `<template #error={error}></template>`. 

Never used [NuxtErrorBoundary](https://nuxt.com/docs/api/components/nuxt-error-boundary) much, but its really interesting as it can save the page from breaking in these kind of scenarios. Lovely stuff!

**Comment by Gugustinette** [comment] 2024-11-04 18:37
Nuxt [v3.14.0](https://github.com/nuxt/nuxt/releases/tag/v3.14.0) was released, and Nuxt Leaflet [1.2.4](https://github.com/nuxt-modules/leaflet/releases/tag/1.2.4) should be updated with it 👍

**Comment by Gugustinette** [comment] 2024-11-04 18:39
As far as I tested, this seems resolved with Nuxt Leaflet 1.2.4.

@tobychidi can you confirm ?

**Comment by Niki2k1** [comment] 2024-11-04 20:08
I can confirm, works with 3.14 on my end 👍🏼

**Comment by tobychidi** [comment] 2024-11-04 20:34
The issue has been resolved. Thank you @Gugustinette

**Comment by Gugustinette** [comment] 2024-11-04 20:39
Cool ! Thanks a lot everyone 👍

**Closed by Gugustinette** 2024-11-04 20:39 UTC
Labels: bug
